# Generated by Django 3.0.4 on 2020-03-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_short_name', models.CharField(max_length=10, unique=True)),
                ('category_name', models.CharField(max_length=64, unique=True)),
                ('category_description', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=16, unique=True)),
                ('product_index', models.PositiveIntegerField(unique=True)),
                ('product_eancode', models.CharField(max_length=16, unique=True)),
                ('product_status', models.CharField(choices=[('AC', 'Active'), ('AR', 'Archive'), ('SO', 'Sell out')], default='AC', max_length=2, unique=True)),
                ('product_description', models.CharField(max_length=64, unique=True)),
                ('product_site_url', models.URLField(max_length=128)),
                ('product_ftp_url', models.URLField(max_length=128)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.Category')),
            ],
        ),
    ]
