# Generated by Django 3.0.6 on 2020-05-27 07:10

import core_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('category_short_name', models.CharField(db_index=True, max_length=10, unique=True)),
                ('category_name', models.CharField(max_length=64, unique=True)),
                ('category_description', models.CharField(blank=True, max_length=256, null=True)),
                ('category_site_url', models.URLField(blank=True, max_length=128, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='categories')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('layout', models.BooleanField(default=False)),
                ('layout_internal_path', models.FilePathField(allow_folders=True, blank=True, max_length=256, null=True, path=core_app.models.network_root_path, recursive=True)),
                ('layout_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('layout_folder_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('maquette', models.BooleanField(default=False)),
                ('maquette_internal_path', models.FilePathField(allow_folders=True, blank=True, max_length=256, null=True, path=core_app.models.network_root_path, recursive=True)),
                ('maquette_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('maquette_folder_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('photos', models.BooleanField(default=False)),
                ('photos_internal_path', models.FilePathField(allow_folders=True, blank=True, max_length=256, null=True, path=core_app.models.network_root_path, recursive=True)),
                ('photos_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('photos_folder_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('photos_3d', models.BooleanField(default=False)),
                ('photos_3d_internal_path', models.FilePathField(allow_folders=True, blank=True, max_length=256, null=True, path=core_app.models.network_root_path, recursive=True)),
                ('photos_3d_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('photos_3d_folder_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('interior_photos', models.BooleanField(default=False)),
                ('interior_photos_internal_path', models.FilePathField(allow_folders=True, blank=True, max_length=256, null=True, path=core_app.models.network_root_path, recursive=True)),
                ('interior_photos_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('interior_photos_folder_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('auxiliary_photos', models.BooleanField(default=False)),
                ('auxiliary_photos_internal_path', models.FilePathField(allow_folders=True, blank=True, max_length=256, null=True, path=core_app.models.network_root_path, recursive=True)),
                ('auxiliary_photos_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('auxiliary_photos_folder_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('manuals', models.BooleanField(default=False)),
                ('manuals_internal_path', models.FilePathField(allow_folders=True, blank=True, max_length=256, null=True, path=core_app.models.network_root_path, recursive=True)),
                ('manuals_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('manuals_photos_folder_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('videos', models.BooleanField(default=False)),
                ('videos_internal_path', models.FilePathField(allow_folders=True, blank=True, max_length=256, null=True, path=core_app.models.network_root_path, recursive=True)),
                ('videos_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('videos_photos_folder_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('descriptions', models.BooleanField(default=False)),
                ('descriptions_internal_path', models.FilePathField(allow_folders=True, blank=True, max_length=256, null=True, path=core_app.models.network_root_path, recursive=True)),
                ('descriptions_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('descriptions_photos_folder_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('characteristics', models.BooleanField(default=False)),
                ('characteristics_internal_path', models.FilePathField(allow_folders=True, blank=True, max_length=256, null=True, path=core_app.models.network_root_path, recursive=True)),
                ('characteristics_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('characteristics_photos_folder_hash', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('product_index', models.PositiveIntegerField(db_index=True, unique=True)),
                ('product_eancode', models.CharField(db_index=True, max_length=16, unique=True)),
                ('product_status', models.CharField(blank=True, choices=[('Z1', 'Z1'), ('ZN', 'ZN'), ('Z9', 'Z9'), ('WS', 'WS'), ('SZ', 'SZ')], db_index=True, default='Z9', max_length=5, null=True)),
                ('product_description', models.CharField(blank=True, max_length=128, null=True)),
                ('marketing_description', models.TextField(blank=True)),
                ('product_site_url', models.URLField(blank=True, max_length=128, null=True)),
                ('product_internal_path', models.URLField(blank=True, max_length=128, null=True)),
                ('product_external_url', models.URLField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rc_complete', models.PositiveSmallIntegerField(default=0)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_app.Category')),
            ],
            options={
                'ordering': ['product_code'],
            },
        ),
    ]
