# Generated by Django 3.0.4 on 2020-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('Z1', 'Active Z1'), ('ZN', 'Active ZN'), ('Z9', 'Active Z9'), ('WS', 'Archive'), ('SZ', 'Sell out')], default='Z9', max_length=2, unique=True),
        ),
    ]
