# Generated by Django 3.0.6 on 2020-05-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20200527_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
