# Generated by Django 3.0.6 on 2020-05-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_auto_20200528_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_manager_name': 'objects', 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
