# Generated by Django 3.0.7 on 2020-06-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_auto_20200529_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='auxiliary_photos_internal_path',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='characteristics_internal_path',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='descriptions_internal_path',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='interior_photos_internal_path',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='layout_internal_path',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='manuals_internal_path',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='maquette_internal_path',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='photos_3d_internal_path',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='photos_internal_path',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='videos_internal_path',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
