# Generated by Django 3.0.7 on 2020-06-12 16:07

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_auto_20200611_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
        migrations.AlterField(
            model_name='content',
            name='auxiliary_photos_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='characteristics_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='descriptions_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='interior_photos_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='layout_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='manuals_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='maquette_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='photos_3d_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='photos_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='product',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core_app.Product'),
        ),
        migrations.AlterField(
            model_name='content',
            name='videos_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
