# Generated by Django 3.0.7 on 2020-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_auto_20200612_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auxiliary_photos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='auxiliary_photos_external_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='auxiliary_photos_folder_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='auxiliary_photos_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics_external_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics_photos_folder_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptions_external_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptions_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptions_photos_folder_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='interior_photos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='interior_photos_external_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='interior_photos_folder_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='interior_photos_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='layout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='layout_external_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='layout_folder_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='layout_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manuals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='manuals_external_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manuals_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manuals_photos_folder_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='maquette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='maquette_external_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='maquette_folder_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='maquette_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='photos_3d',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='photos_3d_external_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photos_3d_folder_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photos_3d_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photos_external_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photos_folder_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photos_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='videos_external_url',
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='videos_internal_path',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='videos_photos_folder_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
