# Generated by Django 3.0.7 on 2020-06-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_auto_20200626_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=16, null=True),
        ),
    ]
