# Generated by Django 3.0.6 on 2020-05-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_parser_app', '0003_auto_20200527_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
